-- Nb heures préventives sur le mois en cours
SELECT SUM(OCCUP.DURATION) AS HEURES_PREV
      FROM CSWO_WO WO INNER JOIN
             CSWO_ACTIONTYPE ACT ON ACT.ID = WO.ACTIONTYPE_ID
                      INNER JOIN
             CSWO_OCCUPATION OCCUP ON OCCUP.WO_ID = WO.ID
      WHERE WOEND BETWEEN {startOfMonth} AND {sysdate}
      AND ACT.CODE not in ('COR_PLANIF','COR_PROD','CORREC','HORS_MAINTENANCE','INS_LEVANO','MISE_EN_SERVICE','MODI','RECONST','REG_LEVREM','SSE','TRNE','VIDANGE_APPOINTS')